//<autogenerated />
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System;

[assembly: CLSCompliantAttribute(true)]

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("LicenseManager")]
[assembly: AssemblyDescription("Provides access to FlexLM license information")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Charles W. Bozarth")]
[assembly: AssemblyProduct("LicenseManager")]
[assembly: AssemblyCopyright("© 2009-2012 Charles W. Bozarth")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("51e88301-f1a5-41dc-b5c0-ffb5b61954fd")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("3.2.*")]
[assembly: AssemblyFileVersion("3.2.0.0")]
